# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.boost.org for most recent version. */
#
# include "staticlib/pimpl/ext_preprocessor/config/config.hpp"
#
# if STATICLIB_PP_CONFIG_FLAGS() & STATICLIB_PP_CONFIG_DMC()
#     include "staticlib/pimpl/ext_preprocessor/detail/dmc/auto_rec.hpp"
# else
#
# ifndef STATICLIB_PREPROCESSOR_DETAIL_AUTO_REC_HPP
# define STATICLIB_PREPROCESSOR_DETAIL_AUTO_REC_HPP
#
# include "staticlib/pimpl/ext_preprocessor/control/iif.hpp"
#
# /* STATICLIB_PP_AUTO_REC */
#
# define STATICLIB_PP_AUTO_REC(pred, n) STATICLIB_PP_NODE_ENTRY_ ## n(pred)
#
# define STATICLIB_PP_NODE_ENTRY_256(p) STATICLIB_PP_NODE_128(p)(p)(p)(p)(p)(p)(p)(p)
# define STATICLIB_PP_NODE_ENTRY_128(p) STATICLIB_PP_NODE_64(p)(p)(p)(p)(p)(p)(p)
# define STATICLIB_PP_NODE_ENTRY_64(p) STATICLIB_PP_NODE_32(p)(p)(p)(p)(p)(p)
# define STATICLIB_PP_NODE_ENTRY_32(p) STATICLIB_PP_NODE_16(p)(p)(p)(p)(p)
# define STATICLIB_PP_NODE_ENTRY_16(p) STATICLIB_PP_NODE_8(p)(p)(p)(p)
# define STATICLIB_PP_NODE_ENTRY_8(p) STATICLIB_PP_NODE_4(p)(p)(p)
# define STATICLIB_PP_NODE_ENTRY_4(p) STATICLIB_PP_NODE_2(p)(p)
# define STATICLIB_PP_NODE_ENTRY_2(p) STATICLIB_PP_NODE_1(p)
#
# define STATICLIB_PP_NODE_128(p) STATICLIB_PP_IIF(p(128), STATICLIB_PP_NODE_64, STATICLIB_PP_NODE_192)
#    define STATICLIB_PP_NODE_64(p) STATICLIB_PP_IIF(p(64), STATICLIB_PP_NODE_32, STATICLIB_PP_NODE_96)
#        define STATICLIB_PP_NODE_32(p) STATICLIB_PP_IIF(p(32), STATICLIB_PP_NODE_16, STATICLIB_PP_NODE_48)
#            define STATICLIB_PP_NODE_16(p) STATICLIB_PP_IIF(p(16), STATICLIB_PP_NODE_8, STATICLIB_PP_NODE_24)
#                define STATICLIB_PP_NODE_8(p) STATICLIB_PP_IIF(p(8), STATICLIB_PP_NODE_4, STATICLIB_PP_NODE_12)
#                    define STATICLIB_PP_NODE_4(p) STATICLIB_PP_IIF(p(4), STATICLIB_PP_NODE_2, STATICLIB_PP_NODE_6)
#                        define STATICLIB_PP_NODE_2(p) STATICLIB_PP_IIF(p(2), STATICLIB_PP_NODE_1, STATICLIB_PP_NODE_3)
#                            define STATICLIB_PP_NODE_1(p) STATICLIB_PP_IIF(p(1), 1, 2)
#                            define STATICLIB_PP_NODE_3(p) STATICLIB_PP_IIF(p(3), 3, 4)
#                        define STATICLIB_PP_NODE_6(p) STATICLIB_PP_IIF(p(6), STATICLIB_PP_NODE_5, STATICLIB_PP_NODE_7)
#                            define STATICLIB_PP_NODE_5(p) STATICLIB_PP_IIF(p(5), 5, 6)
#                            define STATICLIB_PP_NODE_7(p) STATICLIB_PP_IIF(p(7), 7, 8)
#                    define STATICLIB_PP_NODE_12(p) STATICLIB_PP_IIF(p(12), STATICLIB_PP_NODE_10, STATICLIB_PP_NODE_14)
#                        define STATICLIB_PP_NODE_10(p) STATICLIB_PP_IIF(p(10), STATICLIB_PP_NODE_9, STATICLIB_PP_NODE_11)
#                            define STATICLIB_PP_NODE_9(p) STATICLIB_PP_IIF(p(9), 9, 10)
#                            define STATICLIB_PP_NODE_11(p) STATICLIB_PP_IIF(p(11), 11, 12)
#                        define STATICLIB_PP_NODE_14(p) STATICLIB_PP_IIF(p(14), STATICLIB_PP_NODE_13, STATICLIB_PP_NODE_15)
#                            define STATICLIB_PP_NODE_13(p) STATICLIB_PP_IIF(p(13), 13, 14)
#                            define STATICLIB_PP_NODE_15(p) STATICLIB_PP_IIF(p(15), 15, 16)
#                define STATICLIB_PP_NODE_24(p) STATICLIB_PP_IIF(p(24), STATICLIB_PP_NODE_20, STATICLIB_PP_NODE_28)
#                    define STATICLIB_PP_NODE_20(p) STATICLIB_PP_IIF(p(20), STATICLIB_PP_NODE_18, STATICLIB_PP_NODE_22)
#                        define STATICLIB_PP_NODE_18(p) STATICLIB_PP_IIF(p(18), STATICLIB_PP_NODE_17, STATICLIB_PP_NODE_19)
#                            define STATICLIB_PP_NODE_17(p) STATICLIB_PP_IIF(p(17), 17, 18)
#                            define STATICLIB_PP_NODE_19(p) STATICLIB_PP_IIF(p(19), 19, 20)
#                        define STATICLIB_PP_NODE_22(p) STATICLIB_PP_IIF(p(22), STATICLIB_PP_NODE_21, STATICLIB_PP_NODE_23)
#                            define STATICLIB_PP_NODE_21(p) STATICLIB_PP_IIF(p(21), 21, 22)
#                            define STATICLIB_PP_NODE_23(p) STATICLIB_PP_IIF(p(23), 23, 24)
#                    define STATICLIB_PP_NODE_28(p) STATICLIB_PP_IIF(p(28), STATICLIB_PP_NODE_26, STATICLIB_PP_NODE_30)
#                        define STATICLIB_PP_NODE_26(p) STATICLIB_PP_IIF(p(26), STATICLIB_PP_NODE_25, STATICLIB_PP_NODE_27)
#                            define STATICLIB_PP_NODE_25(p) STATICLIB_PP_IIF(p(25), 25, 26)
#                            define STATICLIB_PP_NODE_27(p) STATICLIB_PP_IIF(p(27), 27, 28)
#                        define STATICLIB_PP_NODE_30(p) STATICLIB_PP_IIF(p(30), STATICLIB_PP_NODE_29, STATICLIB_PP_NODE_31)
#                            define STATICLIB_PP_NODE_29(p) STATICLIB_PP_IIF(p(29), 29, 30)
#                            define STATICLIB_PP_NODE_31(p) STATICLIB_PP_IIF(p(31), 31, 32)
#            define STATICLIB_PP_NODE_48(p) STATICLIB_PP_IIF(p(48), STATICLIB_PP_NODE_40, STATICLIB_PP_NODE_56)
#                define STATICLIB_PP_NODE_40(p) STATICLIB_PP_IIF(p(40), STATICLIB_PP_NODE_36, STATICLIB_PP_NODE_44)
#                    define STATICLIB_PP_NODE_36(p) STATICLIB_PP_IIF(p(36), STATICLIB_PP_NODE_34, STATICLIB_PP_NODE_38)
#                        define STATICLIB_PP_NODE_34(p) STATICLIB_PP_IIF(p(34), STATICLIB_PP_NODE_33, STATICLIB_PP_NODE_35)
#                            define STATICLIB_PP_NODE_33(p) STATICLIB_PP_IIF(p(33), 33, 34)
#                            define STATICLIB_PP_NODE_35(p) STATICLIB_PP_IIF(p(35), 35, 36)
#                        define STATICLIB_PP_NODE_38(p) STATICLIB_PP_IIF(p(38), STATICLIB_PP_NODE_37, STATICLIB_PP_NODE_39)
#                            define STATICLIB_PP_NODE_37(p) STATICLIB_PP_IIF(p(37), 37, 38)
#                            define STATICLIB_PP_NODE_39(p) STATICLIB_PP_IIF(p(39), 39, 40)
#                    define STATICLIB_PP_NODE_44(p) STATICLIB_PP_IIF(p(44), STATICLIB_PP_NODE_42, STATICLIB_PP_NODE_46)
#                        define STATICLIB_PP_NODE_42(p) STATICLIB_PP_IIF(p(42), STATICLIB_PP_NODE_41, STATICLIB_PP_NODE_43)
#                            define STATICLIB_PP_NODE_41(p) STATICLIB_PP_IIF(p(41), 41, 42)
#                            define STATICLIB_PP_NODE_43(p) STATICLIB_PP_IIF(p(43), 43, 44)
#                        define STATICLIB_PP_NODE_46(p) STATICLIB_PP_IIF(p(46), STATICLIB_PP_NODE_45, STATICLIB_PP_NODE_47)
#                            define STATICLIB_PP_NODE_45(p) STATICLIB_PP_IIF(p(45), 45, 46)
#                            define STATICLIB_PP_NODE_47(p) STATICLIB_PP_IIF(p(47), 47, 48)
#                define STATICLIB_PP_NODE_56(p) STATICLIB_PP_IIF(p(56), STATICLIB_PP_NODE_52, STATICLIB_PP_NODE_60)
#                    define STATICLIB_PP_NODE_52(p) STATICLIB_PP_IIF(p(52), STATICLIB_PP_NODE_50, STATICLIB_PP_NODE_54)
#                        define STATICLIB_PP_NODE_50(p) STATICLIB_PP_IIF(p(50), STATICLIB_PP_NODE_49, STATICLIB_PP_NODE_51)
#                            define STATICLIB_PP_NODE_49(p) STATICLIB_PP_IIF(p(49), 49, 50)
#                            define STATICLIB_PP_NODE_51(p) STATICLIB_PP_IIF(p(51), 51, 52)
#                        define STATICLIB_PP_NODE_54(p) STATICLIB_PP_IIF(p(54), STATICLIB_PP_NODE_53, STATICLIB_PP_NODE_55)
#                            define STATICLIB_PP_NODE_53(p) STATICLIB_PP_IIF(p(53), 53, 54)
#                            define STATICLIB_PP_NODE_55(p) STATICLIB_PP_IIF(p(55), 55, 56)
#                    define STATICLIB_PP_NODE_60(p) STATICLIB_PP_IIF(p(60), STATICLIB_PP_NODE_58, STATICLIB_PP_NODE_62)
#                        define STATICLIB_PP_NODE_58(p) STATICLIB_PP_IIF(p(58), STATICLIB_PP_NODE_57, STATICLIB_PP_NODE_59)
#                            define STATICLIB_PP_NODE_57(p) STATICLIB_PP_IIF(p(57), 57, 58)
#                            define STATICLIB_PP_NODE_59(p) STATICLIB_PP_IIF(p(59), 59, 60)
#                        define STATICLIB_PP_NODE_62(p) STATICLIB_PP_IIF(p(62), STATICLIB_PP_NODE_61, STATICLIB_PP_NODE_63)
#                            define STATICLIB_PP_NODE_61(p) STATICLIB_PP_IIF(p(61), 61, 62)
#                            define STATICLIB_PP_NODE_63(p) STATICLIB_PP_IIF(p(63), 63, 64)
#        define STATICLIB_PP_NODE_96(p) STATICLIB_PP_IIF(p(96), STATICLIB_PP_NODE_80, STATICLIB_PP_NODE_112)
#            define STATICLIB_PP_NODE_80(p) STATICLIB_PP_IIF(p(80), STATICLIB_PP_NODE_72, STATICLIB_PP_NODE_88)
#                define STATICLIB_PP_NODE_72(p) STATICLIB_PP_IIF(p(72), STATICLIB_PP_NODE_68, STATICLIB_PP_NODE_76)
#                    define STATICLIB_PP_NODE_68(p) STATICLIB_PP_IIF(p(68), STATICLIB_PP_NODE_66, STATICLIB_PP_NODE_70)
#                        define STATICLIB_PP_NODE_66(p) STATICLIB_PP_IIF(p(66), STATICLIB_PP_NODE_65, STATICLIB_PP_NODE_67)
#                            define STATICLIB_PP_NODE_65(p) STATICLIB_PP_IIF(p(65), 65, 66)
#                            define STATICLIB_PP_NODE_67(p) STATICLIB_PP_IIF(p(67), 67, 68)
#                        define STATICLIB_PP_NODE_70(p) STATICLIB_PP_IIF(p(70), STATICLIB_PP_NODE_69, STATICLIB_PP_NODE_71)
#                            define STATICLIB_PP_NODE_69(p) STATICLIB_PP_IIF(p(69), 69, 70)
#                            define STATICLIB_PP_NODE_71(p) STATICLIB_PP_IIF(p(71), 71, 72)
#                    define STATICLIB_PP_NODE_76(p) STATICLIB_PP_IIF(p(76), STATICLIB_PP_NODE_74, STATICLIB_PP_NODE_78)
#                        define STATICLIB_PP_NODE_74(p) STATICLIB_PP_IIF(p(74), STATICLIB_PP_NODE_73, STATICLIB_PP_NODE_75)
#                            define STATICLIB_PP_NODE_73(p) STATICLIB_PP_IIF(p(73), 73, 74)
#                            define STATICLIB_PP_NODE_75(p) STATICLIB_PP_IIF(p(75), 75, 76)
#                        define STATICLIB_PP_NODE_78(p) STATICLIB_PP_IIF(p(78), STATICLIB_PP_NODE_77, STATICLIB_PP_NODE_79)
#                            define STATICLIB_PP_NODE_77(p) STATICLIB_PP_IIF(p(77), 77, 78)
#                            define STATICLIB_PP_NODE_79(p) STATICLIB_PP_IIF(p(79), 79, 80)
#                define STATICLIB_PP_NODE_88(p) STATICLIB_PP_IIF(p(88), STATICLIB_PP_NODE_84, STATICLIB_PP_NODE_92)
#                    define STATICLIB_PP_NODE_84(p) STATICLIB_PP_IIF(p(84), STATICLIB_PP_NODE_82, STATICLIB_PP_NODE_86)
#                        define STATICLIB_PP_NODE_82(p) STATICLIB_PP_IIF(p(82), STATICLIB_PP_NODE_81, STATICLIB_PP_NODE_83)
#                            define STATICLIB_PP_NODE_81(p) STATICLIB_PP_IIF(p(81), 81, 82)
#                            define STATICLIB_PP_NODE_83(p) STATICLIB_PP_IIF(p(83), 83, 84)
#                        define STATICLIB_PP_NODE_86(p) STATICLIB_PP_IIF(p(86), STATICLIB_PP_NODE_85, STATICLIB_PP_NODE_87)
#                            define STATICLIB_PP_NODE_85(p) STATICLIB_PP_IIF(p(85), 85, 86)
#                            define STATICLIB_PP_NODE_87(p) STATICLIB_PP_IIF(p(87), 87, 88)
#                    define STATICLIB_PP_NODE_92(p) STATICLIB_PP_IIF(p(92), STATICLIB_PP_NODE_90, STATICLIB_PP_NODE_94)
#                        define STATICLIB_PP_NODE_90(p) STATICLIB_PP_IIF(p(90), STATICLIB_PP_NODE_89, STATICLIB_PP_NODE_91)
#                            define STATICLIB_PP_NODE_89(p) STATICLIB_PP_IIF(p(89), 89, 90)
#                            define STATICLIB_PP_NODE_91(p) STATICLIB_PP_IIF(p(91), 91, 92)
#                        define STATICLIB_PP_NODE_94(p) STATICLIB_PP_IIF(p(94), STATICLIB_PP_NODE_93, STATICLIB_PP_NODE_95)
#                            define STATICLIB_PP_NODE_93(p) STATICLIB_PP_IIF(p(93), 93, 94)
#                            define STATICLIB_PP_NODE_95(p) STATICLIB_PP_IIF(p(95), 95, 96)
#            define STATICLIB_PP_NODE_112(p) STATICLIB_PP_IIF(p(112), STATICLIB_PP_NODE_104, STATICLIB_PP_NODE_120)
#                define STATICLIB_PP_NODE_104(p) STATICLIB_PP_IIF(p(104), STATICLIB_PP_NODE_100, STATICLIB_PP_NODE_108)
#                    define STATICLIB_PP_NODE_100(p) STATICLIB_PP_IIF(p(100), STATICLIB_PP_NODE_98, STATICLIB_PP_NODE_102)
#                        define STATICLIB_PP_NODE_98(p) STATICLIB_PP_IIF(p(98), STATICLIB_PP_NODE_97, STATICLIB_PP_NODE_99)
#                            define STATICLIB_PP_NODE_97(p) STATICLIB_PP_IIF(p(97), 97, 98)
#                            define STATICLIB_PP_NODE_99(p) STATICLIB_PP_IIF(p(99), 99, 100)
#                        define STATICLIB_PP_NODE_102(p) STATICLIB_PP_IIF(p(102), STATICLIB_PP_NODE_101, STATICLIB_PP_NODE_103)
#                            define STATICLIB_PP_NODE_101(p) STATICLIB_PP_IIF(p(101), 101, 102)
#                            define STATICLIB_PP_NODE_103(p) STATICLIB_PP_IIF(p(103), 103, 104)
#                    define STATICLIB_PP_NODE_108(p) STATICLIB_PP_IIF(p(108), STATICLIB_PP_NODE_106, STATICLIB_PP_NODE_110)
#                        define STATICLIB_PP_NODE_106(p) STATICLIB_PP_IIF(p(106), STATICLIB_PP_NODE_105, STATICLIB_PP_NODE_107)
#                            define STATICLIB_PP_NODE_105(p) STATICLIB_PP_IIF(p(105), 105, 106)
#                            define STATICLIB_PP_NODE_107(p) STATICLIB_PP_IIF(p(107), 107, 108)
#                        define STATICLIB_PP_NODE_110(p) STATICLIB_PP_IIF(p(110), STATICLIB_PP_NODE_109, STATICLIB_PP_NODE_111)
#                            define STATICLIB_PP_NODE_109(p) STATICLIB_PP_IIF(p(109), 109, 110)
#                            define STATICLIB_PP_NODE_111(p) STATICLIB_PP_IIF(p(111), 111, 112)
#                define STATICLIB_PP_NODE_120(p) STATICLIB_PP_IIF(p(120), STATICLIB_PP_NODE_116, STATICLIB_PP_NODE_124)
#                    define STATICLIB_PP_NODE_116(p) STATICLIB_PP_IIF(p(116), STATICLIB_PP_NODE_114, STATICLIB_PP_NODE_118)
#                        define STATICLIB_PP_NODE_114(p) STATICLIB_PP_IIF(p(114), STATICLIB_PP_NODE_113, STATICLIB_PP_NODE_115)
#                            define STATICLIB_PP_NODE_113(p) STATICLIB_PP_IIF(p(113), 113, 114)
#                            define STATICLIB_PP_NODE_115(p) STATICLIB_PP_IIF(p(115), 115, 116)
#                        define STATICLIB_PP_NODE_118(p) STATICLIB_PP_IIF(p(118), STATICLIB_PP_NODE_117, STATICLIB_PP_NODE_119)
#                            define STATICLIB_PP_NODE_117(p) STATICLIB_PP_IIF(p(117), 117, 118)
#                            define STATICLIB_PP_NODE_119(p) STATICLIB_PP_IIF(p(119), 119, 120)
#                    define STATICLIB_PP_NODE_124(p) STATICLIB_PP_IIF(p(124), STATICLIB_PP_NODE_122, STATICLIB_PP_NODE_126)
#                        define STATICLIB_PP_NODE_122(p) STATICLIB_PP_IIF(p(122), STATICLIB_PP_NODE_121, STATICLIB_PP_NODE_123)
#                            define STATICLIB_PP_NODE_121(p) STATICLIB_PP_IIF(p(121), 121, 122)
#                            define STATICLIB_PP_NODE_123(p) STATICLIB_PP_IIF(p(123), 123, 124)
#                        define STATICLIB_PP_NODE_126(p) STATICLIB_PP_IIF(p(126), STATICLIB_PP_NODE_125, STATICLIB_PP_NODE_127)
#                            define STATICLIB_PP_NODE_125(p) STATICLIB_PP_IIF(p(125), 125, 126)
#                            define STATICLIB_PP_NODE_127(p) STATICLIB_PP_IIF(p(127), 127, 128)
#    define STATICLIB_PP_NODE_192(p) STATICLIB_PP_IIF(p(192), STATICLIB_PP_NODE_160, STATICLIB_PP_NODE_224)
#        define STATICLIB_PP_NODE_160(p) STATICLIB_PP_IIF(p(160), STATICLIB_PP_NODE_144, STATICLIB_PP_NODE_176)
#            define STATICLIB_PP_NODE_144(p) STATICLIB_PP_IIF(p(144), STATICLIB_PP_NODE_136, STATICLIB_PP_NODE_152)
#                define STATICLIB_PP_NODE_136(p) STATICLIB_PP_IIF(p(136), STATICLIB_PP_NODE_132, STATICLIB_PP_NODE_140)
#                    define STATICLIB_PP_NODE_132(p) STATICLIB_PP_IIF(p(132), STATICLIB_PP_NODE_130, STATICLIB_PP_NODE_134)
#                        define STATICLIB_PP_NODE_130(p) STATICLIB_PP_IIF(p(130), STATICLIB_PP_NODE_129, STATICLIB_PP_NODE_131)
#                            define STATICLIB_PP_NODE_129(p) STATICLIB_PP_IIF(p(129), 129, 130)
#                            define STATICLIB_PP_NODE_131(p) STATICLIB_PP_IIF(p(131), 131, 132)
#                        define STATICLIB_PP_NODE_134(p) STATICLIB_PP_IIF(p(134), STATICLIB_PP_NODE_133, STATICLIB_PP_NODE_135)
#                            define STATICLIB_PP_NODE_133(p) STATICLIB_PP_IIF(p(133), 133, 134)
#                            define STATICLIB_PP_NODE_135(p) STATICLIB_PP_IIF(p(135), 135, 136)
#                    define STATICLIB_PP_NODE_140(p) STATICLIB_PP_IIF(p(140), STATICLIB_PP_NODE_138, STATICLIB_PP_NODE_142)
#                        define STATICLIB_PP_NODE_138(p) STATICLIB_PP_IIF(p(138), STATICLIB_PP_NODE_137, STATICLIB_PP_NODE_139)
#                            define STATICLIB_PP_NODE_137(p) STATICLIB_PP_IIF(p(137), 137, 138)
#                            define STATICLIB_PP_NODE_139(p) STATICLIB_PP_IIF(p(139), 139, 140)
#                        define STATICLIB_PP_NODE_142(p) STATICLIB_PP_IIF(p(142), STATICLIB_PP_NODE_141, STATICLIB_PP_NODE_143)
#                            define STATICLIB_PP_NODE_141(p) STATICLIB_PP_IIF(p(141), 141, 142)
#                            define STATICLIB_PP_NODE_143(p) STATICLIB_PP_IIF(p(143), 143, 144)
#                define STATICLIB_PP_NODE_152(p) STATICLIB_PP_IIF(p(152), STATICLIB_PP_NODE_148, STATICLIB_PP_NODE_156)
#                    define STATICLIB_PP_NODE_148(p) STATICLIB_PP_IIF(p(148), STATICLIB_PP_NODE_146, STATICLIB_PP_NODE_150)
#                        define STATICLIB_PP_NODE_146(p) STATICLIB_PP_IIF(p(146), STATICLIB_PP_NODE_145, STATICLIB_PP_NODE_147)
#                            define STATICLIB_PP_NODE_145(p) STATICLIB_PP_IIF(p(145), 145, 146)
#                            define STATICLIB_PP_NODE_147(p) STATICLIB_PP_IIF(p(147), 147, 148)
#                        define STATICLIB_PP_NODE_150(p) STATICLIB_PP_IIF(p(150), STATICLIB_PP_NODE_149, STATICLIB_PP_NODE_151)
#                            define STATICLIB_PP_NODE_149(p) STATICLIB_PP_IIF(p(149), 149, 150)
#                            define STATICLIB_PP_NODE_151(p) STATICLIB_PP_IIF(p(151), 151, 152)
#                    define STATICLIB_PP_NODE_156(p) STATICLIB_PP_IIF(p(156), STATICLIB_PP_NODE_154, STATICLIB_PP_NODE_158)
#                        define STATICLIB_PP_NODE_154(p) STATICLIB_PP_IIF(p(154), STATICLIB_PP_NODE_153, STATICLIB_PP_NODE_155)
#                            define STATICLIB_PP_NODE_153(p) STATICLIB_PP_IIF(p(153), 153, 154)
#                            define STATICLIB_PP_NODE_155(p) STATICLIB_PP_IIF(p(155), 155, 156)
#                        define STATICLIB_PP_NODE_158(p) STATICLIB_PP_IIF(p(158), STATICLIB_PP_NODE_157, STATICLIB_PP_NODE_159)
#                            define STATICLIB_PP_NODE_157(p) STATICLIB_PP_IIF(p(157), 157, 158)
#                            define STATICLIB_PP_NODE_159(p) STATICLIB_PP_IIF(p(159), 159, 160)
#            define STATICLIB_PP_NODE_176(p) STATICLIB_PP_IIF(p(176), STATICLIB_PP_NODE_168, STATICLIB_PP_NODE_184)
#                define STATICLIB_PP_NODE_168(p) STATICLIB_PP_IIF(p(168), STATICLIB_PP_NODE_164, STATICLIB_PP_NODE_172)
#                    define STATICLIB_PP_NODE_164(p) STATICLIB_PP_IIF(p(164), STATICLIB_PP_NODE_162, STATICLIB_PP_NODE_166)
#                        define STATICLIB_PP_NODE_162(p) STATICLIB_PP_IIF(p(162), STATICLIB_PP_NODE_161, STATICLIB_PP_NODE_163)
#                            define STATICLIB_PP_NODE_161(p) STATICLIB_PP_IIF(p(161), 161, 162)
#                            define STATICLIB_PP_NODE_163(p) STATICLIB_PP_IIF(p(163), 163, 164)
#                        define STATICLIB_PP_NODE_166(p) STATICLIB_PP_IIF(p(166), STATICLIB_PP_NODE_165, STATICLIB_PP_NODE_167)
#                            define STATICLIB_PP_NODE_165(p) STATICLIB_PP_IIF(p(165), 165, 166)
#                            define STATICLIB_PP_NODE_167(p) STATICLIB_PP_IIF(p(167), 167, 168)
#                    define STATICLIB_PP_NODE_172(p) STATICLIB_PP_IIF(p(172), STATICLIB_PP_NODE_170, STATICLIB_PP_NODE_174)
#                        define STATICLIB_PP_NODE_170(p) STATICLIB_PP_IIF(p(170), STATICLIB_PP_NODE_169, STATICLIB_PP_NODE_171)
#                            define STATICLIB_PP_NODE_169(p) STATICLIB_PP_IIF(p(169), 169, 170)
#                            define STATICLIB_PP_NODE_171(p) STATICLIB_PP_IIF(p(171), 171, 172)
#                        define STATICLIB_PP_NODE_174(p) STATICLIB_PP_IIF(p(174), STATICLIB_PP_NODE_173, STATICLIB_PP_NODE_175)
#                            define STATICLIB_PP_NODE_173(p) STATICLIB_PP_IIF(p(173), 173, 174)
#                            define STATICLIB_PP_NODE_175(p) STATICLIB_PP_IIF(p(175), 175, 176)
#                define STATICLIB_PP_NODE_184(p) STATICLIB_PP_IIF(p(184), STATICLIB_PP_NODE_180, STATICLIB_PP_NODE_188)
#                    define STATICLIB_PP_NODE_180(p) STATICLIB_PP_IIF(p(180), STATICLIB_PP_NODE_178, STATICLIB_PP_NODE_182)
#                        define STATICLIB_PP_NODE_178(p) STATICLIB_PP_IIF(p(178), STATICLIB_PP_NODE_177, STATICLIB_PP_NODE_179)
#                            define STATICLIB_PP_NODE_177(p) STATICLIB_PP_IIF(p(177), 177, 178)
#                            define STATICLIB_PP_NODE_179(p) STATICLIB_PP_IIF(p(179), 179, 180)
#                        define STATICLIB_PP_NODE_182(p) STATICLIB_PP_IIF(p(182), STATICLIB_PP_NODE_181, STATICLIB_PP_NODE_183)
#                            define STATICLIB_PP_NODE_181(p) STATICLIB_PP_IIF(p(181), 181, 182)
#                            define STATICLIB_PP_NODE_183(p) STATICLIB_PP_IIF(p(183), 183, 184)
#                    define STATICLIB_PP_NODE_188(p) STATICLIB_PP_IIF(p(188), STATICLIB_PP_NODE_186, STATICLIB_PP_NODE_190)
#                        define STATICLIB_PP_NODE_186(p) STATICLIB_PP_IIF(p(186), STATICLIB_PP_NODE_185, STATICLIB_PP_NODE_187)
#                            define STATICLIB_PP_NODE_185(p) STATICLIB_PP_IIF(p(185), 185, 186)
#                            define STATICLIB_PP_NODE_187(p) STATICLIB_PP_IIF(p(187), 187, 188)
#                        define STATICLIB_PP_NODE_190(p) STATICLIB_PP_IIF(p(190), STATICLIB_PP_NODE_189, STATICLIB_PP_NODE_191)
#                            define STATICLIB_PP_NODE_189(p) STATICLIB_PP_IIF(p(189), 189, 190)
#                            define STATICLIB_PP_NODE_191(p) STATICLIB_PP_IIF(p(191), 191, 192)
#        define STATICLIB_PP_NODE_224(p) STATICLIB_PP_IIF(p(224), STATICLIB_PP_NODE_208, STATICLIB_PP_NODE_240)
#            define STATICLIB_PP_NODE_208(p) STATICLIB_PP_IIF(p(208), STATICLIB_PP_NODE_200, STATICLIB_PP_NODE_216)
#                define STATICLIB_PP_NODE_200(p) STATICLIB_PP_IIF(p(200), STATICLIB_PP_NODE_196, STATICLIB_PP_NODE_204)
#                    define STATICLIB_PP_NODE_196(p) STATICLIB_PP_IIF(p(196), STATICLIB_PP_NODE_194, STATICLIB_PP_NODE_198)
#                        define STATICLIB_PP_NODE_194(p) STATICLIB_PP_IIF(p(194), STATICLIB_PP_NODE_193, STATICLIB_PP_NODE_195)
#                            define STATICLIB_PP_NODE_193(p) STATICLIB_PP_IIF(p(193), 193, 194)
#                            define STATICLIB_PP_NODE_195(p) STATICLIB_PP_IIF(p(195), 195, 196)
#                        define STATICLIB_PP_NODE_198(p) STATICLIB_PP_IIF(p(198), STATICLIB_PP_NODE_197, STATICLIB_PP_NODE_199)
#                            define STATICLIB_PP_NODE_197(p) STATICLIB_PP_IIF(p(197), 197, 198)
#                            define STATICLIB_PP_NODE_199(p) STATICLIB_PP_IIF(p(199), 199, 200)
#                    define STATICLIB_PP_NODE_204(p) STATICLIB_PP_IIF(p(204), STATICLIB_PP_NODE_202, STATICLIB_PP_NODE_206)
#                        define STATICLIB_PP_NODE_202(p) STATICLIB_PP_IIF(p(202), STATICLIB_PP_NODE_201, STATICLIB_PP_NODE_203)
#                            define STATICLIB_PP_NODE_201(p) STATICLIB_PP_IIF(p(201), 201, 202)
#                            define STATICLIB_PP_NODE_203(p) STATICLIB_PP_IIF(p(203), 203, 204)
#                        define STATICLIB_PP_NODE_206(p) STATICLIB_PP_IIF(p(206), STATICLIB_PP_NODE_205, STATICLIB_PP_NODE_207)
#                            define STATICLIB_PP_NODE_205(p) STATICLIB_PP_IIF(p(205), 205, 206)
#                            define STATICLIB_PP_NODE_207(p) STATICLIB_PP_IIF(p(207), 207, 208)
#                define STATICLIB_PP_NODE_216(p) STATICLIB_PP_IIF(p(216), STATICLIB_PP_NODE_212, STATICLIB_PP_NODE_220)
#                    define STATICLIB_PP_NODE_212(p) STATICLIB_PP_IIF(p(212), STATICLIB_PP_NODE_210, STATICLIB_PP_NODE_214)
#                        define STATICLIB_PP_NODE_210(p) STATICLIB_PP_IIF(p(210), STATICLIB_PP_NODE_209, STATICLIB_PP_NODE_211)
#                            define STATICLIB_PP_NODE_209(p) STATICLIB_PP_IIF(p(209), 209, 210)
#                            define STATICLIB_PP_NODE_211(p) STATICLIB_PP_IIF(p(211), 211, 212)
#                        define STATICLIB_PP_NODE_214(p) STATICLIB_PP_IIF(p(214), STATICLIB_PP_NODE_213, STATICLIB_PP_NODE_215)
#                            define STATICLIB_PP_NODE_213(p) STATICLIB_PP_IIF(p(213), 213, 214)
#                            define STATICLIB_PP_NODE_215(p) STATICLIB_PP_IIF(p(215), 215, 216)
#                    define STATICLIB_PP_NODE_220(p) STATICLIB_PP_IIF(p(220), STATICLIB_PP_NODE_218, STATICLIB_PP_NODE_222)
#                        define STATICLIB_PP_NODE_218(p) STATICLIB_PP_IIF(p(218), STATICLIB_PP_NODE_217, STATICLIB_PP_NODE_219)
#                            define STATICLIB_PP_NODE_217(p) STATICLIB_PP_IIF(p(217), 217, 218)
#                            define STATICLIB_PP_NODE_219(p) STATICLIB_PP_IIF(p(219), 219, 220)
#                        define STATICLIB_PP_NODE_222(p) STATICLIB_PP_IIF(p(222), STATICLIB_PP_NODE_221, STATICLIB_PP_NODE_223)
#                            define STATICLIB_PP_NODE_221(p) STATICLIB_PP_IIF(p(221), 221, 222)
#                            define STATICLIB_PP_NODE_223(p) STATICLIB_PP_IIF(p(223), 223, 224)
#            define STATICLIB_PP_NODE_240(p) STATICLIB_PP_IIF(p(240), STATICLIB_PP_NODE_232, STATICLIB_PP_NODE_248)
#                define STATICLIB_PP_NODE_232(p) STATICLIB_PP_IIF(p(232), STATICLIB_PP_NODE_228, STATICLIB_PP_NODE_236)
#                    define STATICLIB_PP_NODE_228(p) STATICLIB_PP_IIF(p(228), STATICLIB_PP_NODE_226, STATICLIB_PP_NODE_230)
#                        define STATICLIB_PP_NODE_226(p) STATICLIB_PP_IIF(p(226), STATICLIB_PP_NODE_225, STATICLIB_PP_NODE_227)
#                            define STATICLIB_PP_NODE_225(p) STATICLIB_PP_IIF(p(225), 225, 226)
#                            define STATICLIB_PP_NODE_227(p) STATICLIB_PP_IIF(p(227), 227, 228)
#                        define STATICLIB_PP_NODE_230(p) STATICLIB_PP_IIF(p(230), STATICLIB_PP_NODE_229, STATICLIB_PP_NODE_231)
#                            define STATICLIB_PP_NODE_229(p) STATICLIB_PP_IIF(p(229), 229, 230)
#                            define STATICLIB_PP_NODE_231(p) STATICLIB_PP_IIF(p(231), 231, 232)
#                    define STATICLIB_PP_NODE_236(p) STATICLIB_PP_IIF(p(236), STATICLIB_PP_NODE_234, STATICLIB_PP_NODE_238)
#                        define STATICLIB_PP_NODE_234(p) STATICLIB_PP_IIF(p(234), STATICLIB_PP_NODE_233, STATICLIB_PP_NODE_235)
#                            define STATICLIB_PP_NODE_233(p) STATICLIB_PP_IIF(p(233), 233, 234)
#                            define STATICLIB_PP_NODE_235(p) STATICLIB_PP_IIF(p(235), 235, 236)
#                        define STATICLIB_PP_NODE_238(p) STATICLIB_PP_IIF(p(238), STATICLIB_PP_NODE_237, STATICLIB_PP_NODE_239)
#                            define STATICLIB_PP_NODE_237(p) STATICLIB_PP_IIF(p(237), 237, 238)
#                            define STATICLIB_PP_NODE_239(p) STATICLIB_PP_IIF(p(239), 239, 240)
#                define STATICLIB_PP_NODE_248(p) STATICLIB_PP_IIF(p(248), STATICLIB_PP_NODE_244, STATICLIB_PP_NODE_252)
#                    define STATICLIB_PP_NODE_244(p) STATICLIB_PP_IIF(p(244), STATICLIB_PP_NODE_242, STATICLIB_PP_NODE_246)
#                        define STATICLIB_PP_NODE_242(p) STATICLIB_PP_IIF(p(242), STATICLIB_PP_NODE_241, STATICLIB_PP_NODE_243)
#                            define STATICLIB_PP_NODE_241(p) STATICLIB_PP_IIF(p(241), 241, 242)
#                            define STATICLIB_PP_NODE_243(p) STATICLIB_PP_IIF(p(243), 243, 244)
#                        define STATICLIB_PP_NODE_246(p) STATICLIB_PP_IIF(p(246), STATICLIB_PP_NODE_245, STATICLIB_PP_NODE_247)
#                            define STATICLIB_PP_NODE_245(p) STATICLIB_PP_IIF(p(245), 245, 246)
#                            define STATICLIB_PP_NODE_247(p) STATICLIB_PP_IIF(p(247), 247, 248)
#                    define STATICLIB_PP_NODE_252(p) STATICLIB_PP_IIF(p(252), STATICLIB_PP_NODE_250, STATICLIB_PP_NODE_254)
#                        define STATICLIB_PP_NODE_250(p) STATICLIB_PP_IIF(p(250), STATICLIB_PP_NODE_249, STATICLIB_PP_NODE_251)
#                            define STATICLIB_PP_NODE_249(p) STATICLIB_PP_IIF(p(249), 249, 250)
#                            define STATICLIB_PP_NODE_251(p) STATICLIB_PP_IIF(p(251), 251, 252)
#                        define STATICLIB_PP_NODE_254(p) STATICLIB_PP_IIF(p(254), STATICLIB_PP_NODE_253, STATICLIB_PP_NODE_255)
#                            define STATICLIB_PP_NODE_253(p) STATICLIB_PP_IIF(p(253), 253, 254)
#                            define STATICLIB_PP_NODE_255(p) STATICLIB_PP_IIF(p(255), 255, 256)
#
# endif
# endif
